# Generated by Django 4.0.3 on 2023-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('job_position', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=5)),
                ('dateTimeOfPosting', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dateTimeOfPosting'],
            },
        ),
    ]
