# Generated by Django 4.0.3 on 2023-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField()),
                ('like', models.BooleanField(default=False)),
                ('comment', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
