# Generated by Django 4.0.3 on 2023-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTest', '0002_board_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
